name: silent_speech
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - notebook
  - pytorch=2.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - libsndfile
  - absl-py
  - numpy
  - librosa
  - pysoundfile
  - matplotlib
  - scipy
  - numba
  - unidecode
  - tqdm
  - pip
  - pip:
    - jiwer==2.2.1
    - deepspeech==0.9.3
    - praat-textgrids
    - noisereduce
